#!/usr/bin/env bash
# setup-udev.sh — create stable /dev/elrs-tx and /dev/esp32-debug symlinks.
#
# Run on the Raspberry Pi with BOTH devices plugged in.
# The script discovers each USB serial device, shows its identity, then
# writes /etc/udev/rules.d/99-rcsailboat.rules and reloads udev.
#
# After running:
#   /dev/elrs-tx      → ELRS TX module
#   /dev/esp32-debug  → ESP32 USB serial console
#
# Set these in /etc/rcsailboat.env:
#   ELRS_PORT=/dev/elrs-tx
#   ESP32_DBG_PORT=/dev/esp32-debug

set -euo pipefail

RULES_FILE="/etc/udev/rules.d/99-rcsailboat.rules"

if [[ $EUID -ne 0 ]]; then
  echo "Run as root: sudo $0"
  exit 1
fi

echo ""
echo "=== USB serial devices found ==="
echo ""

declare -a DEVS=()
for dev in /dev/ttyUSB* /dev/ttyACM*; do
  [[ -e "$dev" ]] || continue
  DEVS+=("$dev")
done

if [[ ${#DEVS[@]} -eq 0 ]]; then
  echo "No /dev/ttyUSB* or /dev/ttyACM* devices found."
  echo "Plug in the ELRS TX module and ESP32, then re-run."
  exit 1
fi

declare -A DEV_VENDOR DEV_PRODUCT DEV_SERIAL

for dev in "${DEVS[@]}"; do
  info=$(udevadm info --query=all --name="$dev" 2>/dev/null)
  vendor=$(echo "$info"  | awk -F= '/^E: ID_VENDOR_ID=/{print $2}' | head -1)
  product=$(echo "$info" | awk -F= '/^E: ID_MODEL_ID=/{print $2}'  | head -1)
  model=$(echo "$info"   | awk -F= '/^E: ID_MODEL=/{print $2}'     | head -1 | tr '_' ' ')
  serial=$(echo "$info"  | awk -F= '/^E: ID_SERIAL_SHORT=/{print $2}' | head -1)
  mfr=$(echo "$info"     | awk -F= '/^E: ID_VENDOR=/{print $2}'    | head -1 | tr '_' ' ')

  DEV_VENDOR["$dev"]="$vendor"
  DEV_PRODUCT["$dev"]="$product"
  DEV_SERIAL["$dev"]="$serial"

  printf "  %-20s  %s %s  (VID=%s PID=%s serial=%s)\n" \
    "$dev" "$mfr" "$model" "${vendor:--}" "${product:--}" "${serial:-none}"
done

echo ""

# --- Tag each device ---
ELRS_DEV=""
ESP32_DEV=""

if [[ ${#DEVS[@]} -eq 1 ]]; then
  echo "Only one device found. Assign it manually."
  echo ""
  read -r -p "Is ${DEVS[0]} the ELRS TX module? [y/N] " ans
  if [[ "$ans" =~ ^[Yy]$ ]]; then
    ELRS_DEV="${DEVS[0]}"
  else
    ESP32_DEV="${DEVS[0]}"
  fi
else
  echo "Tag each device — enter the number next to it:"
  for i in "${!DEVS[@]}"; do
    echo "  $((i+1))) ${DEVS[$i]}"
  done
  echo ""
  read -r -p "Which device is the ELRS TX module? (number) " n
  ELRS_DEV="${DEVS[$((n-1))]}"
  read -r -p "Which device is the ESP32 USB console?  (number) " n
  ESP32_DEV="${DEVS[$((n-1))]}"
fi

echo ""

# --- Build udev rule lines ---
make_rule() {
  local dev="$1" symlink="$2"
  local vendor="${DEV_VENDOR[$dev]}"
  local product="${DEV_PRODUCT[$dev]}"
  local serial="${DEV_SERIAL[$dev]}"

  local match="ATTRS{idVendor}==\"${vendor}\", ATTRS{idProduct}==\"${product}\""
  # Prefer serial-number match when available (survives port changes)
  if [[ -n "$serial" ]]; then
    match="${match}, ATTRS{serial}==\"${serial}\""
  fi

  echo "SUBSYSTEM==\"tty\", ${match}, SYMLINK+=\"${symlink}\", MODE=\"0660\", GROUP=\"dialout\""
}

RULE_LINES=""
[[ -n "$ELRS_DEV"  ]] && RULE_LINES+="$(make_rule "$ELRS_DEV"  "elrs-tx")"$'\n'
[[ -n "$ESP32_DEV" ]] && RULE_LINES+="$(make_rule "$ESP32_DEV" "esp32-debug")"$'\n'

echo "=== Rules to be written to $RULES_FILE ==="
echo ""
echo "$RULE_LINES"

read -r -p "Write these rules? [Y/n] " confirm
if [[ "$confirm" =~ ^[Nn]$ ]]; then
  echo "Aborted — no changes made."
  exit 0
fi

cat > "$RULES_FILE" <<EOF
# RC Sailboat — stable device symlinks
# Generated by setup-udev.sh on $(date -I)

${RULE_LINES}
EOF

udevadm control --reload-rules
udevadm trigger

echo ""
echo "Done. Unplug and re-plug both devices, then verify:"
echo "  ls -la /dev/elrs-tx /dev/esp32-debug"
echo ""
echo "Update /etc/rcsailboat.env:"
echo "  ELRS_PORT=/dev/elrs-tx"
echo "  ESP32_DBG_PORT=/dev/esp32-debug"
